services:
    tomcat-server:
        image: tomcat:9.0-jdk8
        volumes:
            - ./tienda:/usr/local/tomcat/webapps/tienda
            - ./context.xml:/usr/local/tomcat/conf/context.xml
        ports:
            - 8080:8080
        command:
            - "/bin/sh"
            - "-c"
            - "catalina.sh run"
