services:
    tomcat-server:
      build:
        context: .
        dockerfile: Dockerfile
      volumes:
          - ./tienda/index.html:/usr/local/tomcat/webapps/tienda/index.html
          - ./tienda/images:/usr/local/tomcat/webapps/tienda/images
          - ./tienda/styles:/usr/local/tomcat/webapps/tienda/styles
          - ./context.xml:/usr/local/tomcat/conf/context.xml
      ports:
          - 8080:8080
